version: '3.9'

networks:
  default:
    name: ${PROJECT}-network
    driver: bridge

services:
  postgre:
    image: 'bitnami/postgresql:latest'
    container_name: ${PROJECT}-postgre
    env_file:
      - .env
    ports:
      - "5432:${POSTGRES_PORT}"
    volumes:
        - db_data:/var/lib/postgresql/data

  php:
    image: 'bitnami/php-fpm:latest'
    container_name: ${PROJECT}-php
    depends_on:
      - postgre
    volumes:
      - ./:/app

  nginx:
    image: 'bitnami/nginx:latest'
    container_name: ${PROJECT}-nginx
    depends_on:
      - php
    ports:
      - '8000:80'
      - '4443:443'
    volumes:
      - ../configuration/docker/nginx/server_block.conf:/opt/bitnami/nginx/conf/server_blocks/wanadev-tuto.conf:ro

volumes:
  db_data: ~